[package]
name = "random_struct_layout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version = "*", features = ["full"]}
proc-macro2 = "*"
quote = "*"
rand = "*"
